name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 8 */7 * *'  # Every 7 days at 8:00 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: curl -I https://ryhoeoteonqoihpneuzm.supabase.co/rest/v1/users?select=id&limit=1
